-- MySQL Script generated by MySQL Workbench
-- Mon Jun  3 14:04:16 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema neighbourhoods
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `neighbourhoods` ;

-- -----------------------------------------------------
-- Schema neighbourhoods
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `neighbourhoods` DEFAULT CHARACTER SET utf8mb3 ;
USE `neighbourhoods` ;

-- -----------------------------------------------------
-- Table `neighbourhoods`.`profielen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neighbourhoods`.`profielen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefoonnummer` VARCHAR(45) NOT NULL,
  `wachtwoord` VARCHAR(45) NOT NULL,
  `profielfoto` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `neighbourhoods`.`activiteiten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neighbourhoods`.`activiteiten` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `naam` VARCHAR(45) NOT NULL,
  `beschrijving` TEXT NOT NULL,
  `prijs` VARCHAR(3) NOT NULL,
  `plaats` VARCHAR(45) NOT NULL,
  `datum` DATETIME NOT NULL,
  `maxMensen` VARCHAR(3) NULL,
  `organisator_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_activiteiten_Profielen1_idx` (`organisator_id` ASC) VISIBLE,
  CONSTRAINT `fk_activiteiten_Profielen1`
    FOREIGN KEY (`organisator_id`)
    REFERENCES `neighbourhoods`.`profielen` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `neighbourhoods`.`profielen_has_activiteiten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `neighbourhoods`.`profielen_has_activiteiten` (
  `Profielen_id` INT NOT NULL,
  `activiteiten_id` INT NOT NULL,
  PRIMARY KEY (`Profielen_id`, `activiteiten_id`),
  INDEX `fk_Profielen_has_activiteiten_activiteiten1_idx` (`activiteiten_id` ASC) VISIBLE,
  INDEX `fk_Profielen_has_activiteiten_Profielen_idx` (`Profielen_id` ASC) VISIBLE,
  CONSTRAINT `fk_Profielen_has_activiteiten_activiteiten1`
    FOREIGN KEY (`activiteiten_id`)
    REFERENCES `neighbourhoods`.`activiteiten` (`id`),
  CONSTRAINT `fk_Profielen_has_activiteiten_Profielen`
    FOREIGN KEY (`Profielen_id`)
    REFERENCES `neighbourhoods`.`profielen` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `neighbourhoods`.`profielen`
-- -----------------------------------------------------
START TRANSACTION;
USE `neighbourhoods`;
INSERT INTO `neighbourhoods`.`profielen` (`id`, `naam`, `email`, `telefoonnummer`, `wachtwoord`, `profielfoto`) VALUES (1, 'art', 'art@gmail.com', '03837931', 'Azerty123', NULL);
INSERT INTO `neighbourhoods`.`profielen` (`id`, `naam`, `email`, `telefoonnummer`, `wachtwoord`, `profielfoto`) VALUES (2, 'robin', 'robin@gmail.com', '37128493', 'test', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `neighbourhoods`.`activiteiten`
-- -----------------------------------------------------
START TRANSACTION;
USE `neighbourhoods`;
INSERT INTO `neighbourhoods`.`activiteiten` (`id`, `naam`, `beschrijving`, `prijs`, `plaats`, `datum`, `maxMensen`, `organisator_id`) VALUES (1, 'lopen', 'lopen is leuk', '10', 'hoeksken 74 evergem', '2020-01-01 10:10:10', '10', 1);
INSERT INTO `neighbourhoods`.`activiteiten` (`id`, `naam`, `beschrijving`, `prijs`, `plaats`, `datum`, `maxMensen`, `organisator_id`) VALUES (2, 'schaken', 'schaken is leuk', '0', 'hoeksken 74 evergem', '2020-01-01 10:10:10', '2', 1);
INSERT INTO `neighbourhoods`.`activiteiten` (`id`, `naam`, `beschrijving`, `prijs`, `plaats`, `datum`, `maxMensen`, `organisator_id`) VALUES (3, 'awida', 'awldia', '9', 'hoeksken 74 evergem', '2020-01-01 10:10:10', '3', 2);

COMMIT;


-- -----------------------------------------------------
-- Data for table `neighbourhoods`.`profielen_has_activiteiten`
-- -----------------------------------------------------
START TRANSACTION;
USE `neighbourhoods`;
INSERT INTO `neighbourhoods`.`profielen_has_activiteiten` (`Profielen_id`, `activiteiten_id`) VALUES (1, 1);
INSERT INTO `neighbourhoods`.`profielen_has_activiteiten` (`Profielen_id`, `activiteiten_id`) VALUES (1, 2);
INSERT INTO `neighbourhoods`.`profielen_has_activiteiten` (`Profielen_id`, `activiteiten_id`) VALUES (2, 2);

COMMIT;

